### ISSUE TITLE
the parameters for "list" command may be wrong

### ISSUE THREAD

**Issue by zzpbuaa** [mercedes-benz/odxtools#153]
When I use odxtools list xxx.pdx, it says:
```
Traceback (most recent call last):
  File "D:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\PythonEnvs\py38\lib\site-packages\odxtools\__main__.py", line 7, in <module>
    _main()
  File "D:\PythonEnvs\py38\lib\site-packages\odxtools\__init__.py", line 92, in _main
    _main.start_cli()
  File "D:\PythonEnvs\py38\lib\site-packages\odxtools\cli\main.py", line 54, in start_cli
    tool.run(args)
  File "D:\PythonEnvs\py38\lib\site-packages\odxtools\cli\list.py", line 190, in run
    print_global_neg_responses=args.all or args.global_neg_responses,
AttributeError: 'Namespace' object has no attribute 'global_neg_responses'

```

I found the args may be wrong in file https://github.com/mercedes-benz/odxtools/blob/main/odxtools/cli/list.py#L131.

The parser args:
```
    parser.add_argument(
        "-g",
        "--global-negative-responses",
        default=False,
        action="store_const",
        const=True,
        required=False,
        help="Print a list of the global negative responses for the selected ECUs.",
    )
```

but the code in the main entry https://github.com/mercedes-benz/odxtools/blob/f23b3ddc552313434711fa05d1141b4821497606/odxtools/cli/list.py#L190C74-L190C74:
```
        print_global_neg_responses=args.all or args.global_neg_responses,
```

**Comment by andlaus** [comment]
#154 should fix it. if it doesn't please feel free to re-open the issue...
